--Union »——”Ì
USE TESTDB
GO
CREATE TABLE Table_A
(
	Code INT PRIMARY KEY,
	Name NVARCHAR(10)
)
GO
CREATE TABLE Table_B
(
	Code INT PRIMARY KEY,
	Name NVARCHAR(10)
)
GO
--Table_A œ—Ã —ﬂÊ—œ œ— ÃœÊ· 
INSERT INTO Table_A(Code,Name) VALUES (0,NULL)
INSERT INTO Table_A(Code,Name) VALUES (1,'A')
INSERT INTO Table_A(Code,Name) VALUES (2,'B')
INSERT INTO Table_A(Code,Name) VALUES (3,'C')
INSERT INTO Table_A(Code,Name) VALUES (9,'I')
INSERT INTO Table_A(Code,Name) VALUES (10,NULL)
GO
--Table_B œ—Ã —ﬂÊ—œ œ— ÃœÊ· 
INSERT INTO Table_B(Code,Name) VALUES (0,NULL)
INSERT INTO Table_B(Code,Name) VALUES (1,'A')
INSERT INTO Table_B(Code,Name) VALUES (2,'B')
INSERT INTO Table_B(Code,Name) VALUES (3,'C')
INSERT INTO Table_B(Code,Name) VALUES (4,'D')
INSERT INTO Table_B(Code,Name) VALUES (5,'3')
INSERT INTO Table_B(Code,Name) VALUES (10,NULL)
GO
SELECT * FROM Table_A
SELECT * FROM Table_B
GO
SELECT * FROM Table_A
UNION
SELECT * FROM Table_B
GO
SELECT * FROM Table_A
UNION ALL
SELECT * FROM Table_B
GO

SELECT 'Table_A',* FROM Table_A
UNION
SELECT 'Table_B',* FROM Table_B
GO
---ERROR ANY FILED
SELECT * FROM Table_A
UNION
SELECT Code FROM Table_B
GO
---TYPE FILED ERROR

SELECT Name FROM Table_A
UNION
SELECT Code FROM Table_B
GO

SELECT Name FROM Table_A
UNION
SELECT CAST(Code AS NVARCHAR(MAX)) Code FROM Table_B
GO
SELECT 1 AS N
UNION ALL SELECT 2
UNION ALL SELECT 3
UNION ALL SELECT 4
UNION ALL SELECT 5
UNION ALL SELECT 6

GO
--«‘ —«ò
SELECT * FROM Table_A
INTERSECT
SELECT * FROM Table_B

GO

SELECT * FROM Table_A
EXCEPT
SELECT * FROM Table_B

GO

SELECT * FROM Table_B
EXCEPT
SELECT * FROM Table_A

