USE Northwind
CREATE TABLE #T(ID INT)
BEGIN TRANSACTION
   INSERT INTO #T VALUES(1);
ROLLBACK TRANSACTION

SELECT *FROM  #T


USE Northwind
DECLARE  @T TABLE(ID INT)
BEGIN TRANSACTION
   INSERT INTO @T VALUES(1);
ROLLBACK TRANSACTION

SELECT *FROM  @T