use tempdb
go
CREATE TABLE ST1
(
	C1 INT ,
	C2 NVARCHAR(100),
	C3 NVARCHAR(100)
)
GO
INSERT INTO ST1 VALUES (1,'A1','A2')
INSERT INTO ST1 VALUES (2,'B1','B2')
SELECT * FROM ST1
GO
CREATE TABLE TMP_ST1
(
	C1 INT ,
	C3 NVARCHAR(100),
	C2 NVARCHAR(100)
)
GO
SELECT * FROM TMP_ST1
GO
INSERT INTO TMP_ST1 --VALUES (C1,C3,C2)
SELECT C1,C3,C2 FROM ST1
GO
SELECT * FROM TMP_ST1
SELECT * FROM ST1
GO
DROP TABLE ST1
SP_RENAME 'TMP_ST1','ST1'